language: java

jdk:
  - oraclejdk7
  - oraclejdk8

#after_success:
# TODO
#  - .buildscript/deploy_snapshot.sh

env:
  global:
    # TODO
    #- secure: "TODO"
    #- secure: "TODO"

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
